kind: pipeline
name: default
type: kubernetes

services:
- name: server
  image: node:latest
  commands: 
    - npm i -g json-graphql-server@2.2.3
    - json-graphql-server fixture/mocks.json --p 5000
  detach: true
  environment: 
    NODE_HOST: 0.0.0.0
    NODE_PORT: 5000
  ports: 
  - 5000

steps:   
- name: agent_1
  image: ruby:3.0
  commands: 
    - sleep 20
    - bundle install
    - theorize -d tests
  environment: 
    HOST: server
  depends_on: 
    - server