kind: pipeline
name: default
type: kubernetes

steps:
- name: server
  image: node:latest
  commands: 
    - npm i -g json-graphql-server
    - json-graphql-server fixture/mocks.json
  detach: true
  environment: 
    NODE_HOST: 0.0.0.0
    NODE_PORT: 5000
    
- name: agent_1
  image: ruby:3.0
  commands: 
    - bundle install
    - rspec
  environment: 
    HOST: server
  depends_on: 
    - server