image: "timbru31/ruby-node:latest"

before_script:
  - bundle install
  - npm i -g json-graphql-server@2.2.3

rspec:
  variables:
    NODE_HOST: 0.0.0.0
    NODE_PORT: 5000
    HOST: 127.0.0.1
  stage: test
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        path: coverage/cobertura-coverage.xml
        coverage_format: cobertura
  coverage: '/\(\d+.\d+\%\) covered/'

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
