
version: "3"

services:
  test: 
    build: .
    depends_on:
      - app
    links: 
      - app:localhost
  app:
    build: ./fixture
    environment: 
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5000
    restart: on-failure
    expose: 
      - 5000

    
